title: Default Page
template: default
taxonomies:
  tags: true
create_title: ""
fields:
  title:
    type: title
    display: Title
    localizable: true
  hero_image:
    type: assets
    display: Hero Image
    container: main
    folder: img
    max_files: 1
  abstract:
    display: Abstract
    type: markdown
  content:
    type: markdown
    display: Content
