title: Default Page
taxonomies:
  tags: true
create_title: ""
fields:
  title:
    type: title
    display: Title
    localizable: true
  template:
    type: template
    default: page
  is_hidden:
    display: Hide from navigation
    type: toggle
    default: true
  hero_image:
    type: assets
    display: Hero Image
    container: main
    folder: img
    max_files: 1
  abstract:
    display: Abstract
    type: markdown
  content:
    type: markdown
    container: main
    display: Content
    cheatsheet: true
