title: Default TVPP Page
taxonomies:
  tags: true
create_title: ""
fields:
  title:
    type: title
    display: Title
    localizable: true
  template:
    type: template
    default: page
  is_hidden:
    display: Hide from navigation
    type: toggle
    default: true
  add_dropcap:
    display: Add a dropcap to first paragraph
    type: toggle
    default: false
  short_description:
    type: markdown
    display: Short description
    instructions: A truncated version of this description will display as the teaser in search and other listings. If omitted, a truncated version of the main content below will be used.
  hero_image:
    type: assets
    display: Hero Image
    container: main
    folder: img
    max_files: 1
  abstract:
    display: Abstract
    instructions: This appears in light text directly above the content.
    type: markdown
  
  content:
    type: markdown
    container: main
    display: Content
    cheatsheet: true
