title: Default TVPP Page
create_title: ""
fields:
  title:
    type: title
    display: Title
    localizable: true
  template:
    type: template
    default: page
  images:
    type: section
  hero_image:
    type: assets
    display: Hero Image
    instructions: Full width image at top of page. Horizontal images work best. Leave blank for a page with no image.
    container: main
    folder: img
    max_files: 1
  add_overlay:
    type: toggle
    display: Add contrast overlay to hero image?
    instructions: Toggle this '<b>on</b>' to add a transparent overlay to darken the hero image slightly. This adds contrast when superimposing the title over lighter images.
  text:
    type: section
    display: Page content
  short_description:
    type: markdown
    display: Short description
    instructions: The short description displays as the teaser in search and other listings. If omitted, a truncated version of the main content will be used as the teaser. <b>The short description is not displayed on the page.</b>
  abstract:
    display: Abstract
    instructions: This is displayed directly above the main content in a lighter font. <b>Use this as a page intro or summary.</b>
    type: markdown
  content:
    type: markdown
    container: main
    display: Content
    instructions: This is the main page content. Use a mix of Markdown and HTML where necessary.
    cheatsheet: true
  options:
    type: section
    display: Page content options
  is_hidden:
    display: Hide this page from the navbar?
    instructions: Turn this 'on' to prevent the page from appearing in the navbar.
    type: toggle
    default: true
  add_dropcap:
    display: Add a dropcap to first letter of first paragraph?
    instructions: Toggle 'on' to change first letter of first paragraph into a dropcap.
    type: toggle
    default: false
