collections:
  blog: '/blog/{year}/{month}/{day}/{slug}'
taxonomies:
  tags: '/blog/tags/{slug}'
routes:
  /blog/tags: blog/taxonomies
  /search: search
  /blog/feed:
    layout: feed
    template: feeds/blog
    content_type: atom
  
