collections:
  blog: '/blog/{year}/{month}/{day}/{slug}'
  biographies: '/biographies/{slug}'
  authors: '/authors/{slug}'
taxonomies:
  tags: '/blog/tags/{slug}'
  authors: '/authors/{slug}'
routes:
  /blog/tags: blog/taxonomies
  /blog/authors: blog/authors
  /authors: blog/authors
  /biographies: biographies/index
  /search: search
  /blog/feed:
    layout: feed
    template: feeds/blog
    content_type: atom
